[package]
name = "particle-system-rs"
version = "0.1.0"
authors = ["Cl√©ment Renault <renault.cle@gmail.com>"]

[dependencies]
glium = "0.14"
nalgebra = "0.8"
cgl = "0.1"
ocl = "0.14"
colorify = "0.2"
fps_counter = "0.2"
hertz = "0.2"
